-- V76 curriculum seed. This statement is idempotent and intentionally does not alter schema.
insert into public.playbook_cards (
  code, skill_system, required_level, situation, customer_insight, mindset,
  core_logic, coaching_prompts, is_pro, source_sheet, sort_order, ai_evaluation_rules
) values
  ('v76-playbook-01', 'Xử lý Từ chối & Chốt Sales', 'Pro', 'KH chê phí bảo hiểm quá cao và đòi giảm phí', 'Khách hàng luôn có tâm lý muốn ''thắng'' trong đàm phán hoặc thử xem mức giá thấp nhất có thể là bao nhiêu.', 'Đừng vội hạ giá trị hợp đồng. Hãy dùng kỹ thuật ''Đường giá'' để neo cảm xúc khách hàng, bớt lượt mặc cả.', 'Góc nhìn:
Thay vì hoảng sợ mất deal, hãy xem đây là cơ hội để chứng minh sự chuyên nghiệp. Giảm phí ngay sẽ tạo tiền lệ xấu và giảm giá trị dịch vụ của bạn.

Logic cốt lõi:
Nếu bạn nhượng bộ ngay lập tức, khách hàng sẽ nghĩ bạn bán phá giá. Hãy giữ nguyên giá hoặc chỉ nhượng bộ khi khách hàng chịu cắt giảm một quyền lợi tương đương (Ví dụ: Bỏ quyền lợi thai sản nếu không cần thiết).', 'Dạ em hiểu anh đang cân nhắc chi phí. Tuy nhiên, bảng giá này là chuẩn niêm yết của công ty để đảm bảo quỹ dự phòng bồi thường tốt nhất cho anh. Nếu ngân sách mình đang eo hẹp, em có thể tư vấn cắt giảm tạm thời Quyền lợi A (không quá cần thiết lúc này) để phí giảm xuống mức anh mong muốn nhé.', true, 'V76_Curriculum_Seed', '160', '{"source_schema":"v76_iceberg","roleplay_prompt":"Act as a tough client who is ready to sign a life insurance contract but insists on a 10% discount or commission cut. You will walk away if the agent doesn''t yield, but you might agree if they logically explain why they can''t cut the price or if they offer to remove an unnecessary benefit instead.","iceberg_steps":{"step_1_tinh_huong":"Khách hàng đồng ý tham gia nhưng yêu cầu giảm 10% phí hoặc đòi cắt hoa hồng mới ký.","step_2_insight":"Khách hàng luôn có tâm lý muốn ''thắng'' trong đàm phán hoặc thử xem mức giá thấp nhất có thể là bao nhiêu.","step_3_goc_nhin":"Thay vì hoảng sợ mất deal, hãy xem đây là cơ hội để chứng minh sự chuyên nghiệp. Giảm phí ngay sẽ tạo tiền lệ xấu và giảm giá trị dịch vụ của bạn.","step_4_logic":"Nếu bạn nhượng bộ ngay lập tức, khách hàng sẽ nghĩ bạn bán phá giá. Hãy giữ nguyên giá hoặc chỉ nhượng bộ khi khách hàng chịu cắt giảm một quyền lợi tương đương (Ví dụ: Bỏ quyền lợi thai sản nếu không cần thiết).","step_5_kich_ban":"Dạ em hiểu anh đang cân nhắc chi phí. Tuy nhiên, bảng giá này là chuẩn niêm yết của công ty để đảm bảo quỹ dự phòng bồi thường tốt nhất cho anh. Nếu ngân sách mình đang eo hẹp, em có thể tư vấn cắt giảm tạm thời Quyền lợi A (không quá cần thiết lúc này) để phí giảm xuống mức anh mong muốn nhé."}}'),
  ('v76-playbook-02', 'Nghệ thuật Khai vấn', 'Leader', 'TVV nản chí vì đăng bài Facebook không ai tương tác', 'Đại lý đang bị mất phương hướng (mất chữ G - Goal trong GROW) và đang mong đợi một ''viên thuốc tiên'' từ Leader.', 'Đừng cầm tay chỉ việc, hãy dùng Mô hình GROW để TVV tự tìm ra điểm nghẽn và giải pháp của chính mình.', 'Góc nhìn:
Nếu bạn đưa ngay kịch bản cho họ copy, họ sẽ mãi ỷ lại. Bạn cần hỏi để họ tự phân tích tệp khách hàng của mình.

Logic cốt lõi:
Sử dụng câu hỏi gợi mở để đưa TVV trở lại thực tế (Reality): Bài viết đang phục vụ mục đích gì? Khán giả của họ là ai? Nội dung có chạm đúng nỗi đau không?', 'Chị hiểu cảm giác hụt hẫng của em. Trước khi mình đổi cách viết, em cho chị hỏi: Mục tiêu cụ thể của em khi đăng bài là gì? Em muốn tìm khách lạ hoàn toàn, hay muốn nhắc những người bạn cũ nhớ rằng em đang làm bảo hiểm?', true, 'V76_Curriculum_Seed', '161', '{"source_schema":"v76_iceberg","roleplay_prompt":"Act as a frustrated junior insurance agent. You have been posting copy-pasted articles on Facebook for a month with zero engagement. You want to quit. You expect your Leader (the user) to give you a magic template. Only respond positively if the Leader asks open-ended questions about your goals or target audience instead of just lecturing you.","iceberg_steps":{"step_1_tinh_huong":"Một đại lý mới than vãn: ''Chị ơi, em đăng bài cả tháng nay không ai like hay hỏi mua bảo hiểm, em nản quá''.","step_2_insight":"Đại lý đang bị mất phương hướng (mất chữ G - Goal trong GROW) và đang mong đợi một ''viên thuốc tiên'' từ Leader.","step_3_goc_nhin":"Nếu bạn đưa ngay kịch bản cho họ copy, họ sẽ mãi ỷ lại. Bạn cần hỏi để họ tự phân tích tệp khách hàng của mình.","step_4_logic":"Sử dụng câu hỏi gợi mở để đưa TVV trở lại thực tế (Reality): Bài viết đang phục vụ mục đích gì? Khán giả của họ là ai? Nội dung có chạm đúng nỗi đau không?","step_5_kich_ban":"Chị hiểu cảm giác hụt hẫng của em. Trước khi mình đổi cách viết, em cho chị hỏi: Mục tiêu cụ thể của em khi đăng bài là gì? Em muốn tìm khách lạ hoàn toàn, hay muốn nhắc những người bạn cũ nhớ rằng em đang làm bảo hiểm?"}}'),
  ('v76-playbook-03', 'Xử lý Từ chối & Chốt Sales', 'Rookie', 'Khách hàng muốn gửi ngân hàng vì lãi suất cao hơn', 'Khách hàng đang nhầm lẫn giữa công cụ Đầu tư sinh lời (Ngân hàng) và công cụ Quản trị rủi ro (Bảo hiểm).', 'Tránh tranh luận về con số. Hãy chuyển từ tư duy ''Lãi suất'' sang ''Giá trị bảo vệ'' bằng kỹ thuật kể chuyện (Narrative).', 'Góc nhìn:
Càng mang máy tính ra cãi nhau về lãi suất, bạn càng thua. Hãy đồng thuận với họ về mặt đầu tư, nhưng mở ra góc nhìn về sự rủi ro bất ngờ.

Logic cốt lõi:
Ngân hàng là nơi để tiền sinh ra tiền khi bạn khỏe mạnh. Bảo hiểm là nơi bơm tiền mặt khẩn cấp khi bạn mất khả năng tạo ra tiền. Hai quỹ này phải song hành.', 'Dạ anh nói rất đúng, nếu thuần túy để sinh lời thì gửi ngân hàng chắc chắn cao hơn. Quỹ ngân hàng là để anh xây dựng tương lai khi khỏe mạnh. Nhưng quỹ bảo hiểm này em thiết kế là để ''bơm'' ngay 1 tỷ đồng tiền mặt bảo vệ cái số tiền tiết kiệm kia của anh, lỡ như có biến cố y tế ập đến thì gia đình không phải rút sổ tiết kiệm ra tiêu. Mình có nên chia nhỏ 10% ngân sách qua quỹ này để bảo vệ 90% còn lại không anh?', false, 'V76_Curriculum_Seed', '162', '{"source_schema":"v76_iceberg","roleplay_prompt":"Act as a logical, numbers-driven client. You believe keeping money in the bank is better than buying insurance because of the interest rate. You will dismiss any agent who tries to argue math with you. You will only be convinced if the agent successfully uses the ''Bank for health, Insurance for emergency'' analogy and tells a compelling short story about risk management.","iceberg_steps":{"step_1_tinh_huong":"Khách hàng từ chối: ''Anh mang tiền này gửi tiết kiệm ngân hàng lãi cao hơn nhiều, tội gì mua bảo hiểm sinh lời thấp''.","step_2_insight":"Khách hàng đang nhầm lẫn giữa công cụ Đầu tư sinh lời (Ngân hàng) và công cụ Quản trị rủi ro (Bảo hiểm).","step_3_goc_nhin":"Càng mang máy tính ra cãi nhau về lãi suất, bạn càng thua. Hãy đồng thuận với họ về mặt đầu tư, nhưng mở ra góc nhìn về sự rủi ro bất ngờ.","step_4_logic":"Ngân hàng là nơi để tiền sinh ra tiền khi bạn khỏe mạnh. Bảo hiểm là nơi bơm tiền mặt khẩn cấp khi bạn mất khả năng tạo ra tiền. Hai quỹ này phải song hành.","step_5_kich_ban":"Dạ anh nói rất đúng, nếu thuần túy để sinh lời thì gửi ngân hàng chắc chắn cao hơn. Quỹ ngân hàng là để anh xây dựng tương lai khi khỏe mạnh. Nhưng quỹ bảo hiểm này em thiết kế là để ''bơm'' ngay 1 tỷ đồng tiền mặt bảo vệ cái số tiền tiết kiệm kia của anh, lỡ như có biến cố y tế ập đến thì gia đình không phải rút sổ tiết kiệm ra tiêu. Mình có nên chia nhỏ 10% ngân sách qua quỹ này để bảo vệ 90% còn lại không anh?"}}'),
  ('v76-playbook-04', 'Kỹ năng Thực chiến', 'Leader', 'Chấn chỉnh thái độ tiêu cực của TVV trong Group Team', 'Họ có thể đang gặp áp lực hoặc không hài lòng cá nhân, nhưng việc xả cảm xúc sai chỗ đang phá hoại năng lượng của cả team.', 'Tách bạch hành vi khỏi con người. Sử dụng khung phản hồi SBI để không gây phòng thủ.', 'Góc nhìn:
Tuyệt đối không dán nhãn ''Em dạo này tiêu cực thế''. Hãy dùng SBI (Situation - Behavior - Impact) để nói chuyện dựa trên bằng chứng.

Logic cốt lõi:
Khi bạn mô tả chính xác sự việc (S), hành động cụ thể (B) và tác động của nó (I), người nghe sẽ nhận thức được hậu quả khách quan mà không cảm thấy bị công kích cá nhân.', 'Sáng nay trong group chat team mình (Hoàn cảnh), chị thấy em nhắn vài tin khá gay gắt chê bai chính sách mới (Hành vi). Việc này làm mấy bạn đại lý mới vừa vào nghề cảm thấy rất hoang mang và lo lắng (Tác động). Chiều nay hai chị em mình ngồi cà phê 15 phút, em chia sẻ riêng với chị xem em đang thấy chính sách này bất cập ở chỗ nào nhé?', true, 'V76_Curriculum_Seed', '163', '{"source_schema":"v76_iceberg","roleplay_prompt":"Act as a defensive, veteran insurance agent. You recently complained about the new company policy in the team group chat. Your leader (the user) is confronting you. If the leader uses aggressive or labeling language (''Why are you so negative?''), you will become angry and defensive. If the leader uses the SBI framework (Situation, Behavior, Impact) calmly, you will calm down and explain your real frustrations with the quota.","iceberg_steps":{"step_1_tinh_huong":"Một TVV kỳ cựu liên tục nhắn tin chê bai chính sách thi đua mới của công ty trong nhóm chat Zalo chung, gây hoang mang cho người mới.","step_2_insight":"Họ có thể đang gặp áp lực hoặc không hài lòng cá nhân, nhưng việc xả cảm xúc sai chỗ đang phá hoại năng lượng của cả team.","step_3_goc_nhin":"Tuyệt đối không dán nhãn ''Em dạo này tiêu cực thế''. Hãy dùng SBI (Situation - Behavior - Impact) để nói chuyện dựa trên bằng chứng.","step_4_logic":"Khi bạn mô tả chính xác sự việc (S), hành động cụ thể (B) và tác động của nó (I), người nghe sẽ nhận thức được hậu quả khách quan mà không cảm thấy bị công kích cá nhân.","step_5_kich_ban":"Sáng nay trong group chat team mình (Hoàn cảnh), chị thấy em nhắn vài tin khá gay gắt chê bai chính sách mới (Hành vi). Việc này làm mấy bạn đại lý mới vừa vào nghề cảm thấy rất hoang mang và lo lắng (Tác động). Chiều nay hai chị em mình ngồi cà phê 15 phút, em chia sẻ riêng với chị xem em đang thấy chính sách này bất cập ở chỗ nào nhé?"}}'),
  ('v76-playbook-05', 'Tiêu chuẩn CSKH', 'Rookie', 'Lấy lại tinh thần sau khi khách hủy hợp đồng phút chót', 'Cảm giác bị từ chối khiến TVV đánh đồng sự thất bại của một ''thương vụ'' với sự yếu kém của ''bản thân''.', 'Bền bỉ & Bền động lực. Phục hồi trước khi kiệt sức bằng cách điều chỉnh nhận thức.', 'Góc nhìn:
Rủi ro lớn nhất không phải là mất một cái hợp đồng, mà là để cảm xúc tiêu cực đó phá hỏng năng lượng tư vấn cho 5 khách hàng tiếp theo trong tuần.

Logic cốt lõi:
Áp dụng kỹ năng Quản lý Căng thẳng: Nhận ra tín hiệu suy sụp. Tách rời sự việc (khách chưa sẵn sàng) khỏi cái tôi (mình tư vấn dở). Dừng lại hít thở, không nhắn tin nài nỉ ngay lúc đó.', '(Kịch bản tự nhủ và phản hồi khách): Dừng lại 15 phút uống nước. Sau đó nhắn lại: ''Dạ em hiểu ạ. Việc tham gia bảo hiểm cần sự đồng thuận của cả hai vợ chồng cho an tâm. Dù sao em cũng rất vui vì anh đã hiểu rõ giá trị quỹ dự phòng này. Lúc nào anh chị sắp xếp được, cứ nhắn em hỗ trợ nhé. Chúc anh chị tuần mới vui vẻ!''', false, 'V76_Curriculum_Seed', '164', '{"source_schema":"v76_iceberg","roleplay_prompt":"Act as a client who just canceled an insurance meeting at the last minute because ''my spouse said no''. The agent (user) is responding to you. If the agent acts pushy, desperate, or tries to convince you right then, ignore them or block them. If the agent responds gracefully, acknowledging the spouse''s decision and leaving the door open professionally, respond warmly: ''Thank you for understanding, I will definitely contact you when my wife is ready''.","iceberg_steps":{"step_1_tinh_huong":"Bạn đã tư vấn rất kỹ rã rã 3 tuần, đến ngày hẹn ký hợp đồng thì khách nhắn tin: ''Vợ anh không đồng ý, thôi để khi khác''. Bạn suy sụp.","step_2_insight":"Cảm giác bị từ chối khiến TVV đánh đồng sự thất bại của một ''thương vụ'' với sự yếu kém của ''bản thân''.","step_3_goc_nhin":"Rủi ro lớn nhất không phải là mất một cái hợp đồng, mà là để cảm xúc tiêu cực đó phá hỏng năng lượng tư vấn cho 5 khách hàng tiếp theo trong tuần.","step_4_logic":"Áp dụng kỹ năng Quản lý Căng thẳng: Nhận ra tín hiệu suy sụp. Tách rời sự việc (khách chưa sẵn sàng) khỏi cái tôi (mình tư vấn dở). Dừng lại hít thở, không nhắn tin nài nỉ ngay lúc đó.","step_5_kich_ban":"(Kịch bản tự nhủ và phản hồi khách): Dừng lại 15 phút uống nước. Sau đó nhắn lại: ''Dạ em hiểu ạ. Việc tham gia bảo hiểm cần sự đồng thuận của cả hai vợ chồng cho an tâm. Dù sao em cũng rất vui vì anh đã hiểu rõ giá trị quỹ dự phòng này. Lúc nào anh chị sắp xếp được, cứ nhắn em hỗ trợ nhé. Chúc anh chị tuần mới vui vẻ!''"}}')
on conflict (code) do update set
  skill_system = excluded.skill_system,
  required_level = excluded.required_level,
  situation = excluded.situation,
  customer_insight = excluded.customer_insight,
  mindset = excluded.mindset,
  core_logic = excluded.core_logic,
  coaching_prompts = excluded.coaching_prompts,
  is_pro = excluded.is_pro,
  source_sheet = excluded.source_sheet,
  sort_order = excluded.sort_order,
  ai_evaluation_rules = excluded.ai_evaluation_rules,
  updated_at = now();
