-- V87 Ultimate Leader Playbook. Sinh tự động từ pasted_content_182.txt sau xác thực cấu trúc 4 nguyên tắc + 10 kịch bản.
-- Chỉ thay dữ liệu seed V86/V87 đã audit; không xóa nội dung Admin hoặc nội dung có coaching_logs.
begin;

delete from public.leader_playbook as playbook
where playbook.legacy_source_code like any (array['v86-leader-playbook-%', 'v87-leader-playbook-%']::text[])
  and not exists (
    select 1 from public.coaching_logs as log where log.leader_playbook_id = playbook.id
  );

insert into public.leader_playbook (type, title, content, note, share_text, roleplay_prompt, tags, legacy_source_code)
values
  ('principle', '5 Cấp Độ Lãnh Đạo (Cập nhật)', 'Mức 1: Quyền lực (sợ). Mức 2: Quan hệ (nể). Mức 3: Kết quả (ngưỡng mộ). Mức 4: Phát triển người khác (biết ơn). Sự chuyển dịch từ Mức 1 lên Mức 4 là hành trình từ người quản lý thành một Người Khai Vấn (Coach).', '📌 Dùng khi tự soi chiếu lại phong cách tương tác với team.', 'Một người quản lý giỏi tạo ra kết quả. Nhưng một Lãnh đạo thực thụ tạo ra những người giỏi hơn mình. Tuần mới, chúng ta cùng nhau nâng tầm nhé!', null, array[]::text[], 'v87-leader-playbook-01'),
  ('principle', 'Tư Duy Tảng Băng Trôi (Iceberg Model)', 'Những biểu hiện như đi trễ, giảm tương tác thường chỉ là 10% bề nổi. 90% phần chìm bên dưới có thể là nỗi sợ hãi hoặc áp lực. Sự thấu cảm bắt đầu từ việc khám phá 90% phần chìm này.', '📌 Dùng trước khi bước vào cuộc trò chuyện chấn chỉnh kỷ luật.', 'Những gì chúng ta thấy ở bề ngoài chưa chắc là toàn bộ câu chuyện. Hãy luôn giữ một khoảng lùi thấu cảm trước khi đưa ra đánh giá nhé.', null, array[]::text[], 'v87-leader-playbook-02'),
  ('principle', 'Kỹ thuật 5 Whys (5 Lần Tại Sao)', 'Thay vì vội đưa giải pháp, hãy kiên nhẫn đào sâu bằng cách hỏi ''Tại sao?'' 5 lần. Điều này giúp TVV tự nhận thức nguyên nhân gốc rễ (vd: lười gọi -> sợ từ chối -> thiếu kịch bản) và tự tìm hướng đi.', '📌 Dùng trong các buổi Review kết quả kinh doanh cuối tháng.', 'Đừng vội chữa triệu chứng, hãy tìm gốc rễ của vấn đề. Cùng nhau đặt câu hỏi ''Tại sao'' sẽ giúp chúng ta đi nhanh hơn vào tháng tới!', null, array[]::text[], 'v87-leader-playbook-03'),
  ('principle', 'Lãnh Đạo Phục Vụ (Servant Leadership)', 'Định vị của Leader không phải người đứng trên chỉ việc, mà là người đứng dưới nâng đỡ. Câu hỏi thường trực: ''Anh/Chị có thể hỗ trợ em điều gì để công việc tuần này trôi chảy hơn?''', '📌 Dùng để mở đầu các buổi họp Team hàng tuần.', 'Thành công của leader chính là sự tỏa sáng của các thành viên. Tuần này, anh/chị có thể hỗ trợ mọi người điều gì để công việc trôi chảy hơn?', null, array[]::text[], 'v87-leader-playbook-04'),
  ('coaching', 'CHẠM 01: Xốc lại tinh thần sau rớt Hợp đồng', 'TVV đang rất hụt hẫng sau khi rớt deal phút chót. Hãy bắt đầu bằng sự đồng cảm, sau đó dùng câu hỏi mở: ''Trải nghiệm vừa rồi mang lại cho em góc nhìn mới nào?''', '⏱️ 15 phút 1-1 - Đặt câu hỏi Khai vấn', null, 'Đóng vai đại lý vừa rớt hợp đồng 50 triệu. Bạn rất suy sụp và muốn bỏ nghề. Leader (người dùng) đang nói chuyện với bạn. Chỉ mở lòng nếu họ thấu cảm và đặt câu hỏi mở.', array['Mất động lực']::text[], 'v87-leader-playbook-05'),
  ('coaching', 'CHẠM 02: Tháo gỡ áp lực chỉ tiêu thi đua', 'Khi team lo âu với chỉ tiêu mới, áp dụng khung phản hồi SBI trong trò chuyện riêng sẽ gỡ rối tâm lý hiệu quả, bảo vệ sự tự tin của TVV.', '⏱️ 15 phút 1-1 - Góp ý chân thành, bảo vệ cái tôi', null, 'Đóng vai đại lý đang bực tức vì chỉ tiêu tháng này quá cao, vừa than vãn trên group. Leader (người dùng) gọi riêng. Hãy bảo vệ quan điểm, trừ khi họ áp dụng chuẩn khung SBI.', array['Áp lực chỉ tiêu']::text[], 'v87-leader-playbook-06'),
  ('coaching', 'CHẠM 03: Định hướng lại cách tìm khách online', 'Đại lý mới dễ hụt hẫng khi bài đăng FB không tương tác. Hãy cùng nhìn lại bằng câu hỏi: ''Mình đang mong chốt khách ngay, hay đang gieo mầm tin tưởng?''.', '⏱️ 15 phút định hướng - Tìm lại mục tiêu', null, 'Đóng vai đại lý mới, nản chí vì đăng FB 1 tháng không ai like. Leader (người dùng) đang khai vấn. Nếu họ đưa văn mẫu, hãy tỏ ra chán nản. Nếu họ hỏi về mục tiêu dài hạn, hãy lắng nghe.', array['Mất động lực']::text[], 'v87-leader-playbook-07'),
  ('coaching', 'CHẠM 04: Xoa dịu TVV khi khách VIP khiếu nại', 'TVV hoảng loạn khi bồi thường chậm. Gợi ý Leader làm điểm tựa trước: ''Bình tĩnh nhé, để chị cùng em xử lý''. Sau đó mới hướng dẫn phản hồi khách.', '⏱️ 5 phút cấp cứu cảm xúc - Làm điểm tựa', null, 'Đóng vai TVV đang hoảng loạn, khóc lóc vì bị khách VIP mắng xối xả. Leader (người dùng) đang gọi. Bạn cần được trấn an cảm xúc trước khi nghe bất kỳ hướng dẫn logic nào.', array['Khủng hoảng']::text[], 'v87-leader-playbook-08'),
  ('coaching', 'CHẠM 05: Truyền lửa vượt qua nỗi sợ Cold-call', 'Thay vì nhắc nhở, Leader chọn cách ngồi cạnh, bật loa ngoài và tự tay gọi mẫu vài cuộc. Lãnh đạo làm gương truyền thông điệp mạnh mẽ nhất.', '⏱️ 30 phút Joint-work - Lãnh đạo bằng hành động', null, 'Đóng vai TVV viện cớ bận để không gọi điện vì sợ bị từ chối. Leader (người dùng) yêu cầu bạn gọi. Bạn chống chế cho đến khi họ đề nghị ''gọi mẫu cho bạn xem''.', array['Kỹ năng yếu', 'Mất động lực']::text[], 'v87-leader-playbook-09'),
  ('coaching', 'CHẠM 06: Chuyển hóa mâu thuẫn nội bộ', 'Khi có cọ xát, lắng nghe chủ động từ hai phía mà không phán xét giúp hạ nhiệt căng thẳng. Leader là nhịp cầu thấu cảm.', '⏱️ 20 phút 1-1 - Lắng nghe không phán xét', null, 'Đóng vai đại lý lâu năm bức xúc vì bị nhân viên mới giành khách. Bạn rất nóng giận. Leader (người dùng) hòa giải. Bạn cần cảm thấy mình được lắng nghe hoàn toàn trước khi hạ hỏa.', array['Mâu thuẫn']::text[], 'v87-leader-playbook-10'),
  ('coaching', 'CHẠM 07: Khai vấn mục tiêu đầu tháng', 'Thay vì giao chỉ tiêu, hãy hỏi: ''Tháng này em mong đạt thu nhập bao nhiêu để lo cho kế hoạch gia đình?''. Gắn việc làm với ước mơ cá nhân.', '⏱️ 15 phút 1-1 - Kết nối mục tiêu cá nhân', null, 'Đóng vai đại lý không có động lực đầu tháng. Leader (người dùng) ép số, bạn sẽ làm lơ. Nếu họ hỏi thăm về mục tiêu tài chính cá nhân/gia đình, bạn sẽ chia sẻ mong muốn thực sự.', array['Thiết lập mục tiêu']::text[], 'v87-leader-playbook-11'),
  ('coaching', 'CHẠM 08: Gỡ rối khâu Chốt Sales (Closing)', 'TVV tư vấn hay nhưng ngại chốt. Cùng phân tích: ''Lúc khách nói để suy nghĩ thêm, cảm xúc em thế nào?''. Đi sâu vào nỗi sợ bị từ chối.', '⏱️ 15 phút Roleplay - Phá rào cản tâm lý', null, 'Đóng vai TVV giỏi lý thuyết nhưng sợ khách hàng. Mỗi lần đến đoạn chốt phí là bạn run và xin về. Leader (người dùng) đang coaching để gỡ bỏ nỗi sợ này cho bạn.', array['Kỹ năng yếu']::text[], 'v87-leader-playbook-12'),
  ('coaching', 'CHẠM 09: Nâng tầm ''Ngôi sao bán hàng''', 'Khi Top Performer tự mãn, hãy khơi gợi tầm nhìn: ''Em muốn xây dựng hình ảnh thế nào trong mắt người mới?''. Trao trọng trách giúp họ trưởng thành.', '⏱️ 20 phút Khai vấn - Mở rộng tầm nhìn', null, 'Đóng vai Top Sale tự cao, hay đi trễ vì nghĩ mình mang về nhiều doanh số. Leader (người dùng) nhắc nhở. Bạn sẽ cự cãi trừ khi họ công nhận tài năng và giao cho bạn vai trò ''dẫn dắt người mới''.', array['Kiêu ngạo']::text[], 'v87-leader-playbook-13'),
  ('coaching', 'CHẠM 10: Giữ nhịp chạy số cuối tháng', 'Chỉ còn 3 ngày cuối tháng. Sự động viên: ''Chúng ta cam kết làm thêm 1 hành động nhỏ nào hôm nay?'' sẽ kích hoạt sức mạnh tập thể.', '⏱️ 15 phút họp nhanh - Hợp lực tập thể', null, 'Đóng vai một nhóm đại lý kiệt sức vào ngày 28 cuối tháng, team mới đạt 60% chỉ tiêu. Leader (người dùng) đang họp team. Bạn chỉ lấy lại tinh thần nếu Leader truyền lửa và xắn tay áo làm cùng.', array['Áp lực chỉ tiêu']::text[], 'v87-leader-playbook-14')
on conflict (legacy_source_code) do update set
  type = excluded.type,
  title = excluded.title,
  content = excluded.content,
  note = excluded.note,
  share_text = excluded.share_text,
  roleplay_prompt = excluded.roleplay_prompt,
  tags = excluded.tags;

commit;
