-- V82: Life Insurance Iceberg curriculum batch 2. Source: pasted_content_179.txt.
insert into public.playbook_cards (
  code, skill_system, required_level, situation, customer_insight, mindset,
  core_logic, coaching_prompts, is_pro, source_sheet, sort_order, ai_evaluation_rules
) values
  ('v82-playbook-01', 'Xử lý Từ chối & Chốt Sales', 'Pro', 'Kỹ thuật Neo Giá trong Đàm Phán', 'Khách hàng thường bị ảnh hưởng tâm lý bởi con số đầu tiên họ nghe thấy (Hiệu ứng mỏ neo).', 'Đừng vội giảm phí. Hãy đưa ra gói quyền lợi tối đa trước để ''neo'' giá trị trong đầu khách, sau đó mới hạ dần xuống gói phù hợp.', 'Góc nhìn:
Việc đưa gói cao nhất ra trước không phải để ép khách mua, mà để thiết lập một chuẩn mực bảo vệ toàn diện.

Logic cốt lõi:
Khi bạn hạ từ gói 50 triệu xuống gói 30 triệu, khách sẽ thấy 30 triệu là một ''món hời'' và dễ chốt hơn việc bạn chào gói 30 triệu ngay từ đầu.', 'Dạ, gói VVIP 50 triệu này là phương án bảo vệ trọn vẹn nhất. Nhưng nếu anh muốn tối ưu dòng tiền hiện tại, em sẽ thiết kế lại gói 30 triệu. Anh chỉ cần bỏ bớt phần thai sản, còn quỹ ung thư và nhân thọ vẫn giữ nguyên mức cao nhất nhé.', true, 'V82_LifeInsurance_Iceberg_Batch2', 184, $v82json${"source_schema":"v82_embedded_iceberg","roleplay_prompt":"Bạn đóng vai một khách hàng VIP đang đàm phán mua gói bảo hiểm 100 triệu. Bạn liên tục yêu cầu Đại lý (người dùng) phải cắt hoa hồng hoặc giảm giá thì mới ký. Bạn rất cứng rắn. Người dùng phải dùng kỹ thuật chứng minh giá trị và giữ vững quan điểm để thuyết phục bạn. Đánh giá người dùng dựa trên sự tự tin và lập luận logic.","iceberg_steps":{"step_1_tinh_huong":"Khách hàng ngập ngừng vì tổng phí đóng hàng năm vượt quá dự tính ban đầu của họ.","step_2_insight":"Khách hàng thường bị ảnh hưởng tâm lý bởi con số đầu tiên họ nghe thấy (Hiệu ứng mỏ neo).","step_3_goc_nhin":"Việc đưa gói cao nhất ra trước không phải để ép khách mua, mà để thiết lập một chuẩn mực bảo vệ toàn diện.","step_4_logic":"Khi bạn hạ từ gói 50 triệu xuống gói 30 triệu, khách sẽ thấy 30 triệu là một 'món hời' và dễ chốt hơn việc bạn chào gói 30 triệu ngay từ đầu.","step_5_kich_ban":"Dạ, gói VVIP 50 triệu này là phương án bảo vệ trọn vẹn nhất. Nhưng nếu anh muốn tối ưu dòng tiền hiện tại, em sẽ thiết kế lại gói 30 triệu. Anh chỉ cần bỏ bớt phần thai sản, còn quỹ ung thư và nhân thọ vẫn giữ nguyên mức cao nhất nhé."}}$v82json$::jsonb),
  ('v82-playbook-02', 'Kỹ năng Thực chiến', 'Rookie', 'Kể Chuyện (Narrative) thay vì Đọc Quyền Lợi', 'Khách hàng không mua một tập giấy lộn xộn các con số. Họ mua sự bình an cho gia đình khi rủi ro xảy đến.', 'Đừng làm một cái máy đọc số liệu. Hãy dùng câu chuyện để chạm vào tử huyệt cảm xúc của khách hàng.', 'Góc nhìn:
Thay vì nói ''Anh sẽ được đền bù 500 triệu'', hãy cho họ thấy 500 triệu đó cứu sống một gia đình như thế nào.

Logic cốt lõi:
Áp dụng Công thức kể chuyện 3 bước: Bối cảnh khách hàng tương tự -> Rủi ro ập đến -> Giá trị của hợp đồng bảo hiểm đã cứu họ thế nào.', 'Bảng số liệu này hơi khô khan, em xin kể anh nghe chuyện của anh H. khách cũ của em. Anh ấy cũng bằng tuổi và là trụ cột gia đình như anh. Lúc phát hiện bạo bệnh, thay vì phải bán mảnh đất đang rớt giá, quỹ dự phòng này đã bơm ngay 500 triệu để anh H. yên tâm chữa trị...', false, 'V82_LifeInsurance_Iceberg_Batch2', 185, $v82json${"source_schema":"v82_embedded_iceberg","roleplay_prompt":"Bạn là một khách hàng nam, 40 tuổi, rất lý trí và chuộng số liệu. Bạn cho rằng gửi tiết kiệm ngân hàng tốt hơn mua bảo hiểm. Người dùng phải sử dụng kỹ năng Kể chuyện (Narrative) để chạm vào tử huyệt cảm xúc của bạn (sự an tâm cho con cái, vợ chồng) chứ không phải chỉ so sánh lãi suất. Hãy chấm điểm mức độ thuyết phục của câu chuyện.","iceberg_steps":{"step_1_tinh_huong":"Khách hàng tỏ ra buồn ngủ hoặc liên tục so sánh lãi suất khi bạn đang trình bày bảng minh họa dài hàng chục trang.","step_2_insight":"Khách hàng không mua một tập giấy lộn xộn các con số. Họ mua sự bình an cho gia đình khi rủi ro xảy đến.","step_3_goc_nhin":"Thay vì nói 'Anh sẽ được đền bù 500 triệu', hãy cho họ thấy 500 triệu đó cứu sống một gia đình như thế nào.","step_4_logic":"Áp dụng Công thức kể chuyện 3 bước: Bối cảnh khách hàng tương tự -> Rủi ro ập đến -> Giá trị của hợp đồng bảo hiểm đã cứu họ thế nào.","step_5_kich_ban":"Bảng số liệu này hơi khô khan, em xin kể anh nghe chuyện của anh H. khách cũ của em. Anh ấy cũng bằng tuổi và là trụ cột gia đình như anh. Lúc phát hiện bạo bệnh, thay vì phải bán mảnh đất đang rớt giá, quỹ dự phòng này đã bơm ngay 500 triệu để anh H. yên tâm chữa trị..."}}$v82json$::jsonb),
  ('v82-playbook-03', 'Tiêu chuẩn CSKH', 'Rookie', 'Nhận diện sự kháng cự ngầm (Phi ngôn ngữ)', 'Cơ thể không biết nói dối. Khách hàng đang có khúc mắc nhưng ngại nói thẳng, hoặc cảm thấy bị ép buộc.', 'Đọc vị phi ngôn ngữ để biết lúc nào nên dừng chốt sale và chuyển sang khai vấn khách hàng.', 'Góc nhìn:
Cố gắng thúc ép ký form lúc này sẽ kích hoạt phản xạ phòng thủ. Cần lùi lại một bước để tháo gỡ tâm lý.

Logic cốt lõi:
Sử dụng câu hỏi mở và phản chiếu lại trạng thái của khách hàng để tạo không gian an toàn cho họ chia sẻ.', 'Dạ vâng, tham gia bảo hiểm là một quyết định dài hạn nên cần suy nghĩ kỹ. Nhưng em cảm giác anh vẫn còn lăn tăn điểm nào đó ở gói này phải không ạ? Anh cứ chia sẻ thẳng thắn để em giải đáp, không mua cũng không sao đâu anh.', false, 'V82_LifeInsurance_Iceberg_Batch2', 186, $v82json${"source_schema":"v82_embedded_iceberg","roleplay_prompt":"Đóng vai một khách hàng đang do dự. Ngôn ngữ cơ thể của bạn thể hiện sự đề phòng. Bạn liên tục nói 'Để suy nghĩ thêm'. Nếu đại lý (người dùng) tiếp tục ép chốt sale, hãy từ chối thẳng thừng. Nếu đại lý lùi lại, thấu cảm và đặt câu hỏi mở để tìm hiểu nỗi lo của bạn, hãy mở lòng chia sẻ rằng bạn sợ công ty bảo hiểm lừa đảo không chịu chi trả bồi thường.","iceberg_steps":{"step_1_tinh_huong":"Khách hàng khoanh tay trước ngực, mắt nhìn đi nơi khác, chép miệng và nói 'Ừ để anh suy nghĩ thêm'.","step_2_insight":"Cơ thể không biết nói dối. Khách hàng đang có khúc mắc nhưng ngại nói thẳng, hoặc cảm thấy bị ép buộc.","step_3_goc_nhin":"Cố gắng thúc ép ký form lúc này sẽ kích hoạt phản xạ phòng thủ. Cần lùi lại một bước để tháo gỡ tâm lý.","step_4_logic":"Sử dụng câu hỏi mở và phản chiếu lại trạng thái của khách hàng để tạo không gian an toàn cho họ chia sẻ.","step_5_kich_ban":"Dạ vâng, tham gia bảo hiểm là một quyết định dài hạn nên cần suy nghĩ kỹ. Nhưng em cảm giác anh vẫn còn lăn tăn điểm nào đó ở gói này phải không ạ? Anh cứ chia sẻ thẳng thắn để em giải đáp, không mua cũng không sao đâu anh."}}$v82json$::jsonb),
  ('v82-playbook-04', 'Nghệ thuật Khai vấn', 'Leader', 'Khung Góp Ý SBI chặn đứng thái độ sai lệch', 'Phê bình chung chung (''Em ý thức kém quá'') sẽ khiến đại lý tự ái, chống đối và sinh ra bất mãn nội bộ.', 'Lãnh đạo bằng sự thật, không phán xét con người. Dùng khung SBI để phản hồi hiệu quả.', 'Góc nhìn:
Cần tách bạch Hành vi (đi trễ) khỏi Con người (năng lực của họ). Tập trung vào sự kiện khách quan.

Logic cốt lõi:
Áp dụng khung SBI: Situation (Hoàn cảnh) - Behavior (Hành vi cụ thể) - Impact (Tác động).', 'Sáng nay trong buổi họp team đầu tuần (Situation), chị thấy em đi trễ 30 phút (Behavior). Việc này làm gián đoạn kế hoạch chia sẻ thông tin chung và ảnh hưởng năng lượng của các bạn mới (Impact). Chị muốn lắng nghe xem dạo này em có đang gặp khó khăn gì trong việc sắp xếp thời gian không?', true, 'V82_LifeInsurance_Iceberg_Batch2', 187, $v82json${"source_schema":"v82_embedded_iceberg","roleplay_prompt":"Bạn đóng vai một Đại lý bảo hiểm đã làm việc 6 tháng nhưng 2 tháng nay không có doanh số, bạn đang rất nản, thường xuyên đi họp trễ và muốn xin nghỉ. Người dùng đóng vai Leader của bạn. Người dùng phải sử dụng kỹ năng Lắng nghe chủ động và mô hình GROW/SBI để khai vấn bạn. Nếu người dùng chỉ khuyên bảo sáo rỗng hoặc trách móc, hãy phản ứng hời hợt/chống đối. Nếu họ đặt câu hỏi đúng trọng tâm và dùng khung SBI, hãy dần mở lòng chia sẻ khó khăn thực sự.","iceberg_steps":{"step_1_tinh_huong":"Một đại lý thường xuyên đi trễ trong các buổi họp team sáng thứ Hai, làm ảnh hưởng đến không khí chung.","step_2_insight":"Phê bình chung chung ('Em ý thức kém quá') sẽ khiến đại lý tự ái, chống đối và sinh ra bất mãn nội bộ.","step_3_goc_nhin":"Cần tách bạch Hành vi (đi trễ) khỏi Con người (năng lực của họ). Tập trung vào sự kiện khách quan.","step_4_logic":"Áp dụng khung SBI: Situation (Hoàn cảnh) - Behavior (Hành vi cụ thể) - Impact (Tác động).","step_5_kich_ban":"Sáng nay trong buổi họp team đầu tuần (Situation), chị thấy em đi trễ 30 phút (Behavior). Việc này làm gián đoạn kế hoạch chia sẻ thông tin chung và ảnh hưởng năng lượng của các bạn mới (Impact). Chị muốn lắng nghe xem dạo này em có đang gặp khó khăn gì trong việc sắp xếp thời gian không?"}}$v82json$::jsonb),
  ('v82-playbook-05', 'Kỹ năng Thực chiến', 'Rookie', 'Cấp Cứu Cảm Xúc - Tránh lây lan tiêu cực', 'Nếu mang nguyên cảm giác bực dọc này vào cuộc gọi telesale tiếp theo, khách hàng mới sẽ cảm nhận được năng lượng xấu của bạn.', 'Phục hồi trước khi kiệt sức. Cảm xúc tiêu cực là virus, cần dập tắt ngay trước khi gặp khách hàng tiếp theo.', 'Góc nhìn:
Sự từ chối thuộc về khách hàng, không phản ánh giá trị con người bạn. Bạn cần reset hệ thống cảm xúc.

Logic cốt lõi:
Áp dụng Quy tắc Dừng 5 Phút. Đánh lạc hướng não bộ khỏi tác nhân gây stress bằng hành động vật lý.', 'Ngay lập tức tắt màn hình điện thoại. Không gọi cho khách khác. Uống một ngốc nước lọc, đi dạo một vòng quanh văn phòng hoặc hít thở sâu 5 nhịp để reset năng lượng. Chỉ quay lại làm việc khi nhịp tim đã ổn định.', false, 'V82_LifeInsurance_Iceberg_Batch2', 188, $v82json${"source_schema":"v82_embedded_iceberg","roleplay_prompt":"Act as an objective AI evaluator. The user (an agent) has just faced a harsh rejection. Ask them what their immediate next action is. If they say they will 'call the next client to make up for it' or 'complain to a colleague', advise them on the danger of emotional burnout. If they mention taking a break, drinking water, or doing breathing exercises, praise their emotional intelligence.","iceberg_steps":{"step_1_tinh_huong":"Bạn vừa bị một khách hàng tiềm năng hủy lịch ký hợp đồng vào phút chót với thái độ gay gắt. Bạn đang rất hụt hẫng và tức giận.","step_2_insight":"Nếu mang nguyên cảm giác bực dọc này vào cuộc gọi telesale tiếp theo, khách hàng mới sẽ cảm nhận được năng lượng xấu của bạn.","step_3_goc_nhin":"Sự từ chối thuộc về khách hàng, không phản ánh giá trị con người bạn. Bạn cần reset hệ thống cảm xúc.","step_4_logic":"Áp dụng Quy tắc Dừng 5 Phút. Đánh lạc hướng não bộ khỏi tác nhân gây stress bằng hành động vật lý.","step_5_kich_ban":"Ngay lập tức tắt màn hình điện thoại. Không gọi cho khách khác. Uống một ngốc nước lọc, đi dạo một vòng quanh văn phòng hoặc hít thở sâu 5 nhịp để reset năng lượng. Chỉ quay lại làm việc khi nhịp tim đã ổn định."}}$v82json$::jsonb)
on conflict (code) do update set
  skill_system = excluded.skill_system,
  required_level = excluded.required_level,
  situation = excluded.situation,
  customer_insight = excluded.customer_insight,
  mindset = excluded.mindset,
  core_logic = excluded.core_logic,
  coaching_prompts = excluded.coaching_prompts,
  is_pro = excluded.is_pro,
  source_sheet = excluded.source_sheet,
  sort_order = excluded.sort_order,
  ai_evaluation_rules = excluded.ai_evaluation_rules,
  updated_at = now();
