-- V92: Update only Leader principles. Coaching scripts remain untouched.
begin;
update public.leader_playbook set type = 'principle', prefix = '01', title = '5 Cấp Độ Lãnh Đạo (John Maxwell)', content = 'Để quản trị hiệu quả, Leader cần định vị rõ mình đang tương tác với team ở cấp độ nào:
• Cấp độ 1: Nhân viên nghe vì sợ (Quyền lực).
• Cấp độ 2: Nhân viên nghe vì nể (Quan hệ).
• Cấp độ 3: Nhân viên nghe vì ngưỡng mộ (Kết quả).
• Cấp độ 4: Nhân viên nghe vì được giúp đỡ (Phát triển).', note = null, tags = array[]::text[], share_text = null, roleplay_prompt = null, mini_quiz = '{"question":"🔥 Tình huống: TVV làm theo lời bạn vì bạn luôn đạt danh hiệu MDRT mỗi năm. Theo John Maxwell, bạn đang quản trị ở cấp độ mấy?","options":["A. Cấp độ 2 (Quan hệ)","B. Cấp độ 3 (Kết quả)"],"correct_index":1,"correct_explanation":"Chính xác! Bạn đang dùng thành tích cá nhân để làm gương (Mức 3). Đích đến tiếp theo là Mức 4: Giúp họ cũng đạt MDRT như bạn.","wrong_explanation":"Chưa chính xác. Mức 2 là khi họ làm vì quý mến cá nhân bạn. Ở đây, họ nể phục thành tích MDRT của bạn, đó là Mức 3 (Kết quả)."}'::jsonb where legacy_source_code = 'v88-leader-playbook-01' and type = 'principle';
update public.leader_playbook set type = 'principle', prefix = '02', title = 'Tư Duy Tảng Băng Trôi (Iceberg Model)', content = 'Đừng bao giờ phản ứng ngay với những biểu hiện bề ngoài:
• Bề nổi (10%): Đi làm trễ, than vãn, lười gọi cold-call.
• Phần chìm (90%): Nỗi sợ từ chối, áp lực tài chính, mâu thuẫn ngầm.
💡 Sự thấu cảm bắt đầu từ việc khám phá 90% phần chìm.', note = null, tags = array[]::text[], share_text = null, roleplay_prompt = null, mini_quiz = '{"question":"🔥 Tình huống: Một đại lý mới liên tục trễ deadline nộp báo cáo. Hành động đầu tiên của bạn là gì?","options":["A. Nhắc nhở quy định phạt của văn phòng.","B. Hẹn cà phê hỏi thăm khó khăn dạo này."],"correct_index":1,"correct_explanation":"Chính xác! Khám phá phần chìm (áp lực, khó khăn) trước khi xử lý bề nổi giúp giải quyết triệt để vấn đề.","wrong_explanation":"Khoan đã, việc áp dụng quy định phạt ngay lập tức chỉ mới giải quyết 10% bề nổi và dễ khiến TVV bất mãn. Hãy lùi lại tìm hiểu 90% phần chìm nhé."}'::jsonb where legacy_source_code = 'v88-leader-playbook-02' and type = 'principle';
insert into public.leader_playbook (type, prefix, title, content, note, tags, share_text, roleplay_prompt, mini_quiz, legacy_source_code) values ('principle', '03', 'Kỹ thuật 5 Whys (Đào sâu gốc rễ)', 'Thay vì vội vàng đưa giải pháp, hãy kiên nhẫn cùng TVV hỏi ''Tại sao?'' liên tiếp 5 lần để tự tìm ra gốc rễ vấn đề (VD: Lười gọi -> Vì sợ từ chối -> Vì thiếu kịch bản).', null, array[]::text[], null, null, '{"question":"🔥 Tình huống: TVV nói ''Em không có khách hàng''. Câu hỏi ''Why'' đầu tiên bạn nên dùng là gì?","options":["A. Tại sao em không thử gọi lại danh sách cũ?","B. Tại sao dạo này em lại thấy khó tìm khách vậy?"],"correct_index":1,"correct_explanation":"Chính xác! Đặt câu hỏi mở để họ tự đào sâu vấn đề, thay vì mớm sẵn giải pháp.","wrong_explanation":"Câu hỏi này vô tình đã mớm sẵn giải pháp (gọi danh sách cũ). Kỹ thuật 5 Whys yêu cầu dùng câu hỏi mở để TVV tự đào sâu vấn đề."}'::jsonb, 'v92-leader-principle-03') on conflict (legacy_source_code) do update set type = excluded.type, prefix = excluded.prefix, title = excluded.title, content = excluded.content, note = excluded.note, tags = excluded.tags, share_text = excluded.share_text, roleplay_prompt = excluded.roleplay_prompt, mini_quiz = excluded.mini_quiz;
insert into public.leader_playbook (type, prefix, title, content, note, tags, share_text, roleplay_prompt, mini_quiz, legacy_source_code) values ('principle', '04', 'Lãnh Đạo Phục Vụ (Servant Leadership)', 'Định vị vai trò của Leader không phải là người đứng trên chỉ việc, mà là người đứng dưới để nâng đỡ và dọn đường cho tuyến dưới tỏa sáng.', null, array[]::text[], null, null, '{"question":"🔥 Tình huống: Đâu là câu nói chuẩn xác nhất của một Lãnh đạo phục vụ trong buổi họp đầu tuần?","options":["A. Tuần này ai cam kết mang về 2 hợp đồng?","B. Tuần này anh/chị có thể hỗ trợ team điều gì?"],"correct_index":1,"correct_explanation":"Chính xác! Trọng tâm của Lãnh đạo phục vụ là tháo gỡ rào cản để team hoàn thành tốt công việc.","wrong_explanation":"Đây là cách giao việc mang tính áp đặt (Mức 1). Lãnh đạo phục vụ sẽ tập trung hỏi xem team cần hỗ trợ gì để tự họ đạt được mục tiêu."}'::jsonb, 'v92-leader-principle-04') on conflict (legacy_source_code) do update set type = excluded.type, prefix = excluded.prefix, title = excluded.title, content = excluded.content, note = excluded.note, tags = excluded.tags, share_text = excluded.share_text, roleplay_prompt = excluded.roleplay_prompt, mini_quiz = excluded.mini_quiz;
insert into public.leader_playbook (type, prefix, title, content, note, tags, share_text, roleplay_prompt, mini_quiz, legacy_source_code) values ('principle', '05', 'Khung Phản Hồi Đa Chiều (SBI Model)', 'Cách góp ý để TVV không tự ái:
• Situation (Tình huống): Nêu bối cảnh rõ ràng.
• Behavior (Hành vi): Mô tả sự thật khách quan, không dán nhãn.
• Impact (Tác động): Nói về hậu quả của hành vi đó.', null, array[]::text[], null, null, '{"question":"🔥 Tình huống: Đâu là cách nói chuẩn chữ ''B'' (Behavior) trong khung SBI?","options":["A. Dạo này em làm việc rất thiếu tập trung.","B. Sáng nay em ngắt lời khách hàng 3 lần."],"correct_index":1,"correct_explanation":"Chính xác! Hành vi phải là sự thật đếm được (ngắt lời 3 lần), không dán nhãn cảm tính.","wrong_explanation":"Chưa chuẩn. ''Thiếu tập trung'' là một nhãn dán cảm tính (phán xét), không phải là hành vi khách quan. Hãy dùng sự kiện có thể quan sát được."}'::jsonb, 'v92-leader-principle-05') on conflict (legacy_source_code) do update set type = excluded.type, prefix = excluded.prefix, title = excluded.title, content = excluded.content, note = excluded.note, tags = excluded.tags, share_text = excluded.share_text, roleplay_prompt = excluded.roleplay_prompt, mini_quiz = excluded.mini_quiz;
commit;
