import React, { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, ChevronDown, Loader2, Users } from "lucide-react";
import { fetchHeartbeatHierarchy, type HeartbeatHierarchy, type PilotSession } from "../lib/supabaseContent";

const emptyHeartbeat: HeartbeatHierarchy = { scope: "self", teams: [], users: [], logs: [], summary: { totalLogs: 0, completedInteractions: 0, closedDeals: 0 } };

export function getVisibleHeartbeatMembers(members: HeartbeatHierarchy["users"], currentUser: { id: string; role: string }) {
  return members.filter((member) => {
    if (member.id === currentUser.id) return false;
    if (currentUser.role === "leader") return member.role === "advisor";
    if (currentUser.role === "director") return member.role === "leader" || member.role === "advisor";
    return currentUser.role === "super_admin";
  });
}

export function HeartbeatHierarchyPanel({ session, onLogNew }: { session: PilotSession | null; onLogNew: () => void }) {
  const role = session?.profile.role ?? "advisor";
  const [teamId, setTeamId] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(() => role === "leader" ? session?.userId ?? null : null);
  const [data, setData] = useState<HeartbeatHierarchy>(emptyHeartbeat);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const isAdvisor = role === "advisor";
  const load = () => { setLoading(true); setError(""); void fetchHeartbeatHierarchy({ teamId, userId }).then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Không thể tải Nhịp Đập.")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [teamId, userId]);
  const users = useMemo(() => data.users.filter((user) => !teamId || user.teamId === teamId), [data.users, teamId]);
  const visibleMembers = useMemo(() => getVisibleHeartbeatMembers(users, { id: session?.userId ?? "", role }), [users, session?.userId, role]);
  const scopeLabel = data.scope === "global" ? "Toàn hệ thống" : data.scope === "agency" ? "Phạm vi Agency" : data.scope === "team" ? "Team trực tiếp" : "Cá nhân";
  return <section className="screen-enter space-y-5 pb-10" aria-label="Nhịp Đập khách hàng">
    <header className="relative overflow-hidden rounded-[28px] bg-slate-950 p-7 text-white shadow-2xl sm:p-9"><div className="pointer-events-none absolute -right-10 -top-10 h-48 w-48 rounded-full bg-indigo-500/30 blur-[70px]" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider"><Activity size={13} className="text-emerald-300" />Zero-PII · {scopeLabel}</span><h1 className="mt-4 text-3xl font-black">Nhịp Đập</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-200">Theo dõi cấp độ dịch vụ và kết quả công việc; không lưu tên, số điện thoại hay thông tin khách hàng.</p></div></header>
  <section className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><div className="min-w-0 flex-1"><p className="text-sm font-black text-indigo-900">Góc nhìn Nhịp Đập</p><p className="mt-1 text-xs text-indigo-700">{isAdvisor ? "Bạn chỉ thấy log của chính mình." : "Chỉ hiển thị cấp dưới theo Team và vai trò; scope được kiểm soát ở tầng dữ liệu."}</p></div>{!isAdvisor && <div className="grid gap-2 sm:grid-cols-2"><label className="text-[10px] font-black uppercase tracking-wide text-indigo-700">Team<select value={teamId ?? ""} onChange={(event) => { setTeamId(event.target.value || null); setUserId(role === "leader" ? session?.userId ?? null : null); }} className="mt-1 block w-full min-w-44 rounded-lg border border-indigo-200 bg-white p-2 text-sm font-bold text-slate-800"><option value="">{role === "leader" ? "Team trực tiếp" : "Tất cả Team trong phạm vi"}</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="text-[10px] font-black uppercase tracking-wide text-indigo-700">Thành viên<select value={userId ?? ""} onChange={(event) => setUserId(event.target.value || null)} className="mt-1 block w-full min-w-44 rounded-lg border border-indigo-200 bg-white p-2 text-sm font-bold text-slate-800"><option value="">{role === "leader" ? "Tất cả Team / chọn TVV" : "Tất cả cấp dưới"}</option>{role === "leader" && session && <option value={session.userId}>Của riêng tôi</option>}{visibleMembers.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>)}</select></label></div>}<button type="button" onClick={onLogNew} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-indigo-700"><CalendarDays size={16} />Ghi Nhịp Đập</button></div></section>
    {error ? <div className="rounded-xl border border-rose-100 bg-rose-50 p-4 text-sm text-rose-700"><strong>Không thể tải dữ liệu.</strong> {error}</div> : loading ? <div className="flex min-h-64 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white text-sm text-slate-500"><Loader2 size={18} className="animate-spin text-indigo-500" />Đang tổng hợp Nhịp Đập…</div> : <><div className="grid gap-3 sm:grid-cols-3">{[{ label: "Bản ghi", value: data.summary.totalLogs, icon: Activity }, { label: "Tương tác hoàn tất", value: data.summary.completedInteractions, icon: Users }, { label: "Nhịp chốt", value: data.summary.closedDeals, icon: ChevronDown }].map((item) => { const Icon = item.icon; return <article key={item.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Icon size={17} className="text-indigo-500" /><strong className="mt-3 block text-3xl font-black text-slate-900">{item.value}</strong><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-slate-400">{item.label}</p></article>; })}</div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-base font-black text-slate-900">Lịch sử Nhịp Đập</h2><p className="mt-1 text-xs text-slate-500">Chỉ có service level, kết quả và ngày follow-up — không có PII khách hàng.</p></div><div className="divide-y divide-slate-100">{data.logs.length ? data.logs.map((log) => <article key={log.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-slate-800">{log.displayName} <span className="font-medium text-slate-400">· {log.teamName}</span></p><p className="mt-1 text-xs text-slate-500">Cấp độ {log.serviceLevel} · {log.actionResult}{log.followUpDate ? ` · Follow-up ${new Date(log.followUpDate).toLocaleDateString("vi-VN")}` : ""}</p></div><time className="text-xs font-medium text-slate-400">{new Date(log.createdAt).toLocaleString("vi-VN")}</time></article>) : <p className="p-8 text-center text-sm text-slate-400">Chưa có bản ghi trong phạm vi đã chọn.</p>}</div></section></>}</section>;
}
