import React, { useMemo, useState } from "react";
import { ArrowUpRight, Flame, HeartHandshake, Target, UserRoundPlus, Users, Wand2, X } from "lucide-react";
import { calculateAdvisorTargetPlan, type TargetRole } from "../lib/sprint11Logic";
import type { TeamGoalDefaults } from "../lib/supabaseContent";

export type Sprint11TargetSave =
  | { role: "advisor"; bhntIncome: number; pntIncome: number; bhntCommission: number; pntCommission: number; bhntContractSize: number; pntContractSize: number }
  | { role: "leader" | "director"; personalIncome: number; recruitmentOutreach: number; activeRatePercent: number; coachingSessions: number; xpBudget: number; teamStreak7dMembers: number };

type LeaderGoalValue = { personalIncome: number; recruitmentOutreach: number; activeRatePercent: number; coachingSessions: number; xpBudget: number; teamStreak7dMembers: number };
type Props = {
  role: TargetRole;
  initialAdvisor: { bhntIncome: number; pntIncome: number; bhntCommission: number; pntCommission: number; bhntContractSize: number; pntContractSize: number };
  initialLeader: LeaderGoalValue;
  teamDefaults?: TeamGoalDefaults | null;
  onClose: () => void;
  onSave: (value: Sprint11TargetSave) => void | Promise<void>;
};

const asMillions = (value: number) => value ? String(Math.round(value / 1_000_000)) : "";
const numeric = (value: string) => Number(value.replace(/[^0-9]/g, "")) || 0;
const inputClass = "mt-1 w-full rounded-lg border bg-white p-2 font-bold outline-none transition focus:ring-2";

function LeaderGoalForm({ values, onChange }: { values: Record<keyof LeaderGoalValue, string>; onChange: (key: keyof LeaderGoalValue, value: string) => void }) {
  const field = (key: keyof LeaderGoalValue, label: string, placeholder: string, color: string, suffix?: string, ariaLabel = label) => <label className={`block text-[11px] font-bold uppercase ${color}`}>{label}<div className="relative"><input aria-label={ariaLabel} inputMode="numeric" value={values[key]} onChange={(event) => onChange(key, event.target.value.replace(/[^0-9]/g, ""))} placeholder={placeholder} className={`${inputClass} ${color.includes("amber") ? "border-amber-200 text-amber-900 focus:border-amber-500 focus:ring-amber-100" : color.includes("emerald") ? "border-emerald-200 text-emerald-900 focus:border-emerald-500 focus:ring-emerald-100" : color.includes("indigo") ? "border-indigo-200 text-indigo-900 focus:border-indigo-500 focus:ring-indigo-100" : "border-slate-200 text-slate-900 focus:border-blue-500 focus:ring-blue-100"}`} />{suffix && <span className={`pointer-events-none absolute right-3 top-3 font-bold ${color}`}>{suffix}</span>}</div></label>;
  return <div className="space-y-4 text-left"><div className="mb-4 rounded-lg bg-blue-50 p-3 text-xs font-medium text-blue-800">Copilot theo dõi <strong>Đầu vào</strong> (Input) của bạn. Quản trị tốt bốn trụ cột hành động này, kết quả doanh số sẽ có nền tảng để đến bền vững.</div><section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="mb-3 flex items-center gap-2 border-b border-slate-100 pb-2 text-sm font-black text-slate-800"><Target size={16} className="text-slate-600" />1. Cá nhân (Làm gương)</h3>{field("personalIncome", "Thu nhập cá nhân kỳ vọng (triệu)", "30", "text-slate-500")}</section><section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="mb-3 flex items-center gap-2 border-b border-amber-100 pb-2 text-sm font-black text-amber-900"><UserRoundPlus size={16} />2. Tuyển dụng (Mở rộng)</h3>{field("recruitmentOutreach", "Ứng viên tiếp cận / phỏng vấn", "10", "text-amber-700")}<p className="mt-1 text-[10px] text-amber-600">Đo lường nỗ lực đầu vào để xây dựng tuyến tư vấn viên mới.</p></section><section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="mb-3 flex items-center gap-2 border-b border-emerald-100 pb-2 text-sm font-black text-emerald-900"><Flame size={16} />3. Kích hoạt Đội ngũ (Active)</h3>{field("activeRatePercent", "Tỷ lệ Active mục tiêu", "50", "text-emerald-700", "%")}<p className="mt-1 text-[10px] text-emerald-600">Copilot dùng Nhịp Đập thực chiến để theo dõi tỷ lệ TVV duy trì hoạt động.</p></section><section className="rounded-xl border border-indigo-200 bg-indigo-50 p-4"><h3 className="mb-3 flex items-center gap-2 border-b border-indigo-100 pb-2 text-sm font-black text-indigo-900"><HeartHandshake size={16} />4. Hỗ trợ & Giữ người (Coaching)</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{field("coachingSessions", "Số ca Coaching gỡ rối", "10", "text-indigo-700", undefined, "Số ca Coaching 1:1")}{field("xpBudget", "Ngân sách thưởng", "5000", "text-indigo-700", "XP")}</div><p className="mt-2 text-[10px] text-indigo-600">Dùng XP để thưởng nóng và vinh danh trong Team theo quỹ được cấp.</p></section></div>;
}

export function Sprint11TargetModal({ role, initialAdvisor, initialLeader, teamDefaults = null, onClose, onSave }: Props) {
  const [bhntIncome, setBhntIncome] = useState(asMillions(initialAdvisor.bhntIncome));
  const [pntIncome, setPntIncome] = useState(asMillions(initialAdvisor.pntIncome));
  const [bhntCommission, setBhntCommission] = useState(String(initialAdvisor.bhntCommission || 40));
  const [pntCommission, setPntCommission] = useState(String(initialAdvisor.pntCommission || 15));
  const [bhntSize, setBhntSize] = useState(asMillions(initialAdvisor.bhntContractSize || 25_000_000));
  const [pntSize, setPntSize] = useState(asMillions(initialAdvisor.pntContractSize || 8_000_000));
  const [leaderDraft, setLeaderDraft] = useState<Record<keyof LeaderGoalValue, string>>({ personalIncome: asMillions(initialLeader.personalIncome), recruitmentOutreach: String(initialLeader.recruitmentOutreach || ""), activeRatePercent: String(initialLeader.activeRatePercent || ""), coachingSessions: String(initialLeader.coachingSessions || ""), xpBudget: String(initialLeader.xpBudget || ""), teamStreak7dMembers: String(initialLeader.teamStreak7dMembers || "") });
  const [saving, setSaving] = useState(false);
  const advisorPlan = useMemo(() => calculateAdvisorTargetPlan({ incomeTarget: numeric(bhntIncome) * 1_000_000, commissionRate: numeric(bhntCommission), averageContractSize: numeric(bhntSize) * 1_000_000 }, { incomeTarget: numeric(pntIncome) * 1_000_000, commissionRate: numeric(pntCommission), averageContractSize: numeric(pntSize) * 1_000_000 }), [bhntIncome, pntIncome, bhntCommission, pntCommission, bhntSize, pntSize]);
  const numberInput = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLInputElement>) => setter(event.target.value.replace(/[^0-9]/g, ""));
  const applyTeamDefaults = () => { if (!teamDefaults) return; setBhntCommission(String(teamDefaults.bhntCommissionPercent)); setBhntSize(asMillions(teamDefaults.bhntContractSize)); setPntCommission(String(teamDefaults.pntCommissionPercent)); setPntSize(asMillions(teamDefaults.pntContractSize)); };
  const isPlayerCoach = role === "leader" || role === "director";
  const save = async () => { setSaving(true); try { if (role === "advisor") { await onSave({ role, bhntIncome: numeric(bhntIncome) * 1_000_000, pntIncome: numeric(pntIncome) * 1_000_000, bhntCommission: numeric(bhntCommission), pntCommission: numeric(pntCommission), bhntContractSize: numeric(bhntSize) * 1_000_000, pntContractSize: numeric(pntSize) * 1_000_000 }); return; } await onSave({ role: role as "leader" | "director", personalIncome: numeric(leaderDraft.personalIncome) * 1_000_000, recruitmentOutreach: numeric(leaderDraft.recruitmentOutreach), activeRatePercent: Math.min(100, numeric(leaderDraft.activeRatePercent)), coachingSessions: numeric(leaderDraft.coachingSessions), xpBudget: numeric(leaderDraft.xpBudget), teamStreak7dMembers: numeric(leaderDraft.teamStreak7dMembers) }); } finally { setSaving(false); } };
  return <div className="store-backdrop sprint6-backdrop" role="dialog" aria-modal="true" aria-labelledby="sprint11-target-title" onMouseDown={onClose}><section className="target-modal sprint11-target-modal" onMouseDown={(event) => event.stopPropagation()}><button className="store-close" onClick={onClose} aria-label="Đóng mục tiêu"><X size={20} /></button><div className="target-modal-icon">{isPlayerCoach ? <Users size={25} /> : <Target size={25} />}</div><span>{isPlayerCoach ? `MỤC TIÊU PLAYER-COACH · ${role === "director" ? "DIRECTOR" : "LEADER"}` : "MỤC TIÊU CÁ NHÂN · TVV"}</span><h2 id="sprint11-target-title">{isPlayerCoach ? <>Mục Tiêu Quản Trị<br /><em>· Bốn Trụ Cột Đầu Vào</em></> : <>Tháng này, bạn muốn<br /><em>chinh phục điều gì?</em></>}</h2><p>{isPlayerCoach ? "Thiết lập bốn cam kết thực chiến để làm gương, mở rộng đội ngũ, giữ Active Rate và giữ người qua coaching." : "Tách riêng BHNT/PNT: mỗi sản phẩm có hoa hồng và size hợp đồng trung bình riêng."}</p>{role === "advisor" ? <><button type="button" onClick={applyTeamDefaults} disabled={!teamDefaults} className="mb-3 flex items-center gap-1 text-xs font-bold text-indigo-500 disabled:cursor-not-allowed disabled:text-slate-400"><Wand2 size={12} />{teamDefaults ? "Điền tự động theo trung bình Team" : "Team chưa cấu hình tham số mặc định"}</button><div className="sprint11-product-grid"><fieldset><legend>BHNT · Thu nhập cá nhân</legend><label>Thu nhập mục tiêu (triệu)<input inputMode="numeric" value={bhntIncome} onChange={numberInput(setBhntIncome)} placeholder="30" /></label><label>Hoa hồng BHNT (%)<input inputMode="numeric" value={bhntCommission} onChange={numberInput(setBhntCommission)} placeholder="40" /></label><label>Size HĐ BHNT (triệu)<input inputMode="numeric" value={bhntSize} onChange={numberInput(setBhntSize)} placeholder="25" /></label><strong>{advisorPlan.bhntContracts} HĐ BHNT</strong></fieldset><fieldset><legend>PNT · Thu nhập cá nhân</legend><label>Thu nhập mục tiêu (triệu)<input inputMode="numeric" value={pntIncome} onChange={numberInput(setPntIncome)} placeholder="10" /></label><label>Hoa hồng PNT (%)<input inputMode="numeric" value={pntCommission} onChange={numberInput(setPntCommission)} placeholder="15" /></label><label>Size HĐ PNT (triệu)<input inputMode="numeric" value={pntSize} onChange={numberInput(setPntSize)} placeholder="8" /></label><strong>{advisorPlan.pntContracts} HĐ PNT</strong></fieldset></div><div className="sprint11-plan-note"><b>{advisorPlan.requiredContracts} HĐ dự kiến</b><span>{advisorPlan.requiredMeetings} cuộc gặp: 1 khám phá + tối đa 2 chạm theo mỗi HĐ.</span></div></> : <LeaderGoalForm values={leaderDraft} onChange={(key, value) => setLeaderDraft((current) => ({ ...current, [key]: value }))} />}<button className="target-save cta-glow" onClick={() => void save()} disabled={saving}>{saving ? "Đang lưu…" : isPlayerCoach ? "Lưu 4 Trụ cột Đầu vào" : "Lưu mục tiêu cá nhân"}<ArrowUpRight size={17} /></button></section></div>;
}
